apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nodejs-app
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-nodejs-app
  template:
    metadata:
      labels:
        app: test-nodejs-app
    spec:
      containers:
        - name: test-nodejs-app
          image: omareltamasehy/newapp:v1
          env:
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 3000